DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(200) UNIQUE NOT NULL,
  email VARCHAR(200) UNIQUE NOT NULL,
  email_verified_at DATETIME NULL DEFAULT NULL,
  email_confirmed VARCHAR(1) NULL DEFAULT '0',
  password VARCHAR(30) NOT NULL,
  remember_token TEXT NULL DEFAULT NULL,
  created_at DATETIME NULL DEFAULT NULL,
  updated_at DATETIME NULL DEFAULT NULL
);

